id: analytics_test
namespace: hoangngbot

tasks:
    - id: task1
      type: io.kestra.plugin.scripts.python.Commands

      namespaceFiles:
          enabled: true

      beforeCommands:
          - apk add --no-cache g++ gcc libffi-dev musl-dev
          - pip install -r ./data_sim/requirements.txt

      commands:
          - python ./data_sim/src/simulation/main.py

triggers:
    - id: schedule
      type: io.kestra.plugin.core.trigger.Schedule
      cron: "*/5 * * * *"
